<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>YoloCadOnnxModel</AssemblyName>
    <RootNamespace>RapidOcrPro.Ai</RootNamespace>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="model\best.onnx" LogicalName="RapidOcrPro.Ai.Models.best.onnx" />
  </ItemGroup>
</Project>
